MySite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView  #通用视图


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    # path('pwd_reset/',include('password_reset.urls',namespace='password_reset')),
    path('article/',include('article.urls',namespace='article')),
    path('home/',TemplateView.as_view(template_name='home.html'),name='home'),
    path('image/',include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #静态目录配置url访问路径

article/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/3/27 下午 10:07

from django.urls import path,re_path
from . import views
from . import list_views

app_name = "article"

urlpatterns = [
    path('article_column/',views.article_column,name='article_column'),
    path('rename_column/',views.rename_article_column,name='rename_article_column'),
    path('del_column/',views.del_article_column,name='del_article_column'),
    path('article_post/',views.article_post,name='article_post'),
    path('article_list/',views.article_list,name='article_list'),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del_article/', views.del_article, name="del_article"),
    path('redit_article/<int:article_id>/', views.redit_article, name="redit_article"),
    path('list_article_titles/', list_views.article_titles, name="article_titles"),
    path('list_article_titles/<username>/', list_views.article_titles, name="author_articles"),
    re_path('list_article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    path('like_article/',list_views.like_article,name='like_article'),
    path('article_tag/',views.article_tag,name='article_tag'),
    path('del_article_tag/',views.del_article_tag,name='del_article_tag'),
    path('test/',views.test),
]

blog/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/3/24 下午 04:17

from django.urls import path
from . import views


app_name = "blog"  #指定app的名称，否则会报错

urlpatterns = [
    path("",views.blog_title,name='blog_title'),
    path('<int:id>/',views.blog_article,name='blog_details'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
# Create your models here.

class ArticleColumn(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='article_column')  #外键，代表一对多关系
    column = models.CharField(max_length=200)
    create = models.DateField(auto_now_add=True)

    # def __str__(self):
    #     return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='tag')
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='article')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn,on_delete=models.CASCADE, related_name='article')
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)   #对应setting.py 中的配置如下：TIME_ZONE = 'Asia/Shanghai'
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User,related_name='articles_like',blank=True)  #多对多关系,会新建一张表存储对应关系,只需要在一个类中声明一个字段即可
    article_tag = models.ManyToManyField(ArticleTag,related_name='article_tag')
    class Meta:
        ordering = ('title',)
        index_together = (('id','slug'),) #对这两个对象建立索引

    def __str__(self):
        return self.title
    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost,self).save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id,self.slug])
    def a(self):
        return reverse('article:list_article_detail',args=[self.id,self.slug])



class Comment(models.Model):
    article = models.ForeignKey(ArticlePost,on_delete=models.CASCADE,related_name='comments')
    commentator = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return "comment by {} on {}".format(self.commentator.username,self.article)

article/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/3/27 下午 09:57

from django import forms
from .models import ArticleColumn,ArticlePost,Comment,ArticleTag

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator','body',)


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)

article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn,ArticlePost,ArticleTag
from .forms import ArticleColumnForm,ArticlePostForm,ArticleTagForm
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST,require_GET
from django.http import HttpResponse
from django.shortcuts import get_object_or_404  #一般在展示文章时候使用
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger   #内置分页函数
import json
# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user_id=request.user.id)
        column_form = ArticleColumnForm()
        return render(request,'article/column/article_column.html',{'columns':columns,'column_form':column_form})
    if request.method == 'POST':
        column_name = request.POST.get('column')
        columns = ArticleColumn.objects.filter(user_id=request.user.id,column=column_name)
        if columns:
            return HttpResponse('have exist')
        else:
            ArticleColumn.objects.create(user_id=request.user.id,column=column_name)
            return HttpResponse('success')


@login_required(login_url='/account/login')
@require_POST   #只接受POST数据
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id,user_id=request.user.id)  #安全问题修复
        line.column = column_name
        line.save()
        return HttpResponse('1')
    except:
        return HttpResponse('0')

@login_required(login_url='account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST.get('column_id')
    try:
        line = ArticleColumn.objects.get(user_id=request.user.id,id=column_id)
        line.delete()
        return HttpResponse(1)
    except:
        return HttpResponse(0)

@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)  #可以直接用此方法格式化为字典对象
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data

            try:
                new_article = article_post_form.save(commit=False)
                # 当你通过表单获取你的模型数据，但是需要给模型里其他字段添加一些非表单的数据，该方法会非常有用。
                # 如果你指定commit = False，那么save方法不会理解将表单数据存储到数据库，而是给你返回一个当前对象
                # 。这时你可以添加表单以外的额外数据，再一起存储。
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tag']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)  #关系表新增加一条记录
                return HttpResponse('1')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('3')
    else:
        article_post_form = ArticlePostForm()
        article_tags = request.user.tag.all()
        article_columns = request.user.article_column.all()   #因为models 外键中的这个参数  related_name='article_column'(可以找到article_column中所有该用户的实例，注意是实例)
        return render(request,'article/column/article_post.html',{'article_post_form':article_post_form,'article_columns':article_columns,
                                                                  'article_tags':article_tags})


@login_required(login_url='/account/login')
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)  #request.user是用户名str
    for a in articles:
        print(a.column)  #返回的事ArticleColumn实例
        print(a.column.column)  #实例的字段值
    return render(request,'article/column/article_list.html',{'articles':articles})


@login_required(login_url='/account/login')
@require_GET
def article_detail(request,id,slug):
    article = get_object_or_404(ArticlePost,id=id,slug=slug,author_id=request.user.id)
    return render(request,'article/column/article_detail.html',{'article':article})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request,article_id):
    if request.method == 'GET':
        article_columns = request.user.article_column.all()  #获取ArticleColumn字符串对象集（QuerySet）
        print(article_columns)
        article = ArticlePost.objects.get(id=article_id)    #获取单一article实例
        this_article_form = ArticlePostForm(initial={'title':article.title})   #获取渲染完的表单
        print(article.column)  #算是一个实例，这一列
        print(article.column.column)   #关联到article_column数据库的column字段
        print(type(article.column))  #<class 'article.models.ArticleColumn'>
        print(type(article.column.column))   #<class 'str'>
        this_article_column = article.column
        return render(request,'article/column/redit_article.html',{'article':article,'article_columns':article_columns,'this_article_form':this_article_form,
                                                                   'this_article_column':this_article_column})

    if request.method == 'POST':
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id']) #?????????
            print(redit_article.column)  #一个ArticleColumn对象   ArticleColumn object (1)
            print(request.user)
            print(request.user.article_column)
            print(request.user.article_column.get(id=request.POST['column_id']))
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required(login_url='/account/login')
def article_list(request):
    article_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(article_list,8)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:  #页码不是整数
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:  #页码是空
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request,'article/column/article_list.html',{'articles':articles,
                                                              'page':current_page})

@login_required(login_url='/account/login/')
@csrf_exempt    #无法防止csrf
def article_tag(request):
    if request.method == 'GET':
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request,'article/tag/tag_list.html',{'article_tags':article_tags,
                                                           'article_tag_form':article_tag_form})
    if request.method == 'POST':
        tag_post_form = ArticleTagForm(request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse('1')
            except:
                return HttpResponse('post data error')
        else:
            return HttpResponse('the form is not valid')


@login_required(login_url='/account/login/')
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')


@login_required(login_url='/account/login')
def test(request):
    print(request.user)
    return HttpResponse('this is test page')

templates/article/list/article_detail.html
{% extends "article/base.html" %}
{% load article_tags %}
{% load static %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}

{%  with total_likes=article.users_like.count users_like=article.users_like.all %}
<div>
    <header>
        <h1>{{ article.title }}</h1>
        <p><a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
            <span style="margin-left: 20px" class="glyphicon glyphicon-thumbs-up">{{ total_likes }} like{{ total_likes | pluralize }}</span>
            <span style="margin-left: 20px">{{ total_views }} view{{ total_views | pluralize }}</span>
            <span style="margin-left: 20px">该用户共发表了{% author_total_articles article.author %}篇文章</span>   {# 用户直接用user也可以 #}
        </p>
        <p><span style="margin-right: 10px"><strong>Tags:</strong></span>{{ article.article_tag.all | join:',' }} </p>
    </header>
     <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
    <div id="editormd-view">
        <textarea id="append-test" style="display: none;">
            {{ article.body }}
        </textarea>
    </div>


    <div>
        <p class="text-center"><h3>最新文章</h3></p>
        {% latest_articles %}
    </div>
    <hr>
<p class="text-center"><h3>最多评论的文章</h3></p>
{% most_commented_articles as most_comments %}
<ul>
    {%  for article in most_comments %}
    <li>
        <a href="{{ article.a }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>

<hr>
<p class="text-center"><h3>推荐相似文章</h3></p>
{% for article in similar_articles %}
<p><a href="{{ article.a }}">{{ article.title }}</a> </p>
{% empty %}
<p>没有相似文章</p>
{% endfor %}


    <div>
        <p class="text-center">
            <a onclick="like_article({{ article.id }},'like')" href="#"><span class="glyphicon glyphicon-thumbs-up">like</span> </a>
            <a onclick="like_article({{ article.id }},'unlike')" href="#"><span class="glyphicon glyphicon-thumbs-up">unlike</span> </a>
        </p>
    </div>
    <div>
        <p class="text-center"><strong>点赞本文的读者</strong></p>
        {% for user in article.users_like.all %}
        <p class="text-center">{{ user.username }}</p>
        {% empty %}
        <p class="text-center">没有人对此文章表态</p>
        {% endfor %}
    </div>
    <hr>
    <div>
        <h3><span class="glyphicon glyphicon-bullhorn"></span>有{{ article.comments.count }} 条评论</h3>
        {% for comment in article.comments.all %}
        <p><strong>{{ comment.commentator }}</strong>评论了：</p>
            <p style="margin-left: 40px">{{ comment.body }}</p>

    </div>
        {% empty %}
            <p>没有评论</p>
        {% endfor %}
<h3><span class="glyphicon glyphicon-send"></span>说点什么吧 </h3>
<form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">昵称</label>
        <div class="col-sm-10">
            {{ comment_form.commentator }}
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
        <div class="col-sm-10">
            {{ comment_form.body }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <p><input type="submit" name="" value="发评论" class="btn btn-primary"></p>
        </div>

    </div>
</form>
</div>


<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript" src="{% static 'layui/lay/modules/layer.js' %}"></script>
<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList:true,
        tex:true,
        flowChart:true,
        sequenceDiagram : true,
    });
});
</script>




<script type="text/javascript">
function like_article(id,action) {
    $.ajax({
        url:"{% url 'article:like_article' %}",
        type: "POST",
        data:{'id':id,'action':action},
        success:function(e) {
            if (e == '1') {
                layer.msg("点赞成功");
                window.location.reload();
            } else {
                layer.msg('取消成功');
                window.location.reload();

            }
        },
    });
}
</script>



{% endwith %}
{% endblock %}

templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} articles {% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>文章列表</h1>
{#    <p>这里已经有{{ page.paginator.num_pages }}篇文章供你阅读</p>#}
    <p>这里已经有{% total_articles %}篇文章供你阅读</p>
</div>
<div class="container">
    {% for article in articles %} 
    <div class="list-group">
        <a href="{{ article.a }}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4> 
        </a>
        <p class="list-group-item-text">作者: <a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <p class="list-group-item-text">概要:{{article.body|slice:'150'| linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %} 
</div>
{% endblock %}

templates/article/list/author_articles.html
{% extends "base.html" %}
{% load static %}
{% load article_tags %}
{% block title %}articles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>文章列表</h1>
</div>
<div class="container"> 
<div class="col-md-8">
    {% for article in articles %} 
    <div class="list-group">
        <a href="{{article.a}}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4>
        </a>
        <p class="list-group-item-text">作者:
            <a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a>
        </p>

        <p class="list-group-item-text">概要:{{article.body|slice:'70'|linebreaks}} </p>
    </div>
    {% endfor %}
    {% include "paginator.html" %} 
</div>
<div class="col-md-4">
<div>
    {% if userinfo.photo %}
    <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face" style="width: 300px"> 
    {% else %}
    <img name="user_face" src="{% static 'images/newton.jpg' %}" class="img-circle" id="my_photo" style="width: 300px">
    {% endif %}
</div>
<div>
    <p>{{ user.username }}</p>
    <P>共发表了{% author_total_articles user %}篇文章</P>
{% if userinfo %}
    <p>{{ userinfo.company }}</p>
    <p>{{ userinfo.aboutme }}</p>
{% else %} 
    <p>这个作者太懒了，什么也没有留下。</p> 
{% endif %}
</div>
</div>
</div>
{% endblock %}

templates/article/list/latest_articles.html
<ul>
    {%  for article in latest_articles %}
    <li>
        <a href="{{ article.a }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>