MySite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView  #通用视图


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    # path('pwd_reset/',include('password_reset.urls',namespace='password_reset')),
    path('article/',include('article.urls',namespace='article')),
    path('home/',TemplateView.as_view(template_name='home.html'),name='home'),
    path('image/',include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #静态目录配置url访问路径

account/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/3/25 下午 04:35

from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy #防止硬编码


app_name = 'account'


urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='account/login2.html'),name='auth_login'),
    # path('login/',views.user_login,name='auth_login'),
    # path('login/',auth_views.LoginView.as_view(template_name='account/login2.html'),name = 'auth_login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='account/logout.html'),name = 'auth_logout'),
    path('register/',views.register,name = 'user_register'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html',
                                                                  success_url=reverse_lazy('account:auth_passwordchange_done')),name = 'auth_passwordchange'),
    path('password_change_done/',auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),name = 'auth_passwordchange_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",
                                                                 email_template_name="account/password_reset_email.html",
                                                                 success_url=reverse_lazy('account:password_reset_done')),name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",
                                                     success_url=reverse_lazy('account:password_reset_down')),name="password_reset_confirm"),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('my_information/',views.myself,name='my_information'),
    path('edit_my_information/',views.myself_edit,name='my_information_edit'),
    path('my_image/',views.my_image,name='my_image')

]

article/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/3/27 下午 10:07

from django.urls import path,re_path
from . import views
from . import list_views

app_name = "article"

urlpatterns = [
    path('article_column/',views.article_column,name='article_column'),
    path('rename_column/',views.rename_article_column,name='rename_article_column'),
    path('del_column/',views.del_article_column,name='del_article_column'),
    path('article_post/',views.article_post,name='article_post'),
    path('article_list/',views.article_list,name='article_list'),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del_article/', views.del_article, name="del_article"),
    path('redit_article/<int:article_id>/', views.redit_article, name="redit_article"),
    path('list_article_titles/', list_views.article_titles, name="article_titles"),
    path('list_article_titles/<username>/', list_views.article_titles, name="author_articles"),
    re_path('list_article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    path('like_article/',list_views.like_article,name='like_article'),
    path('article_tag/',views.article_tag,name='article_tag'),
    path('del_article_tag/',views.del_article_tag,name='del_article_tag'),
    path('test/',views.test),
]

blog/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/3/24 下午 04:17

from django.urls import path
from . import views


app_name = "blog"  #指定app的名称，否则会报错

urlpatterns = [
    path("",views.blog_title,name='blog_title'),
    path('<int:id>/',views.blog_article,name='blog_details'),
]

course/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/4/2 上午 10:27

from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'course'

urlpatterns = [
    #path('about/',TemplateView.as_view(template_name='course/about.html')),  #直接返回template不经过view（类模板文件）
    path('about/',views.AboutView.as_view(),name='about'),  #或者这样，继承父类，赋值变量
    path('course_list/',views.CourseListView.as_view(),name='course_list'),

]

image/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Archerx
# @time: 2019/4/1 下午 09:34
from django.urls import path
from . import views

app_name = 'image'

urlpatterns = [
    path('list_images/', views.list_images, name="list_images"),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('del_image/', views.del_image, name='del_image'),
    path('images/',views.falls_images,name='falls_images')

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascript %}
        {% endblock %}
    </body>
</html>

templates/footer.html
<div class="container"> <hr>
    <p class="text-center">CopyRight  <a href="https://blog.ixuchao.cn">blog.ixuchao.cn</a></p>
</div>

templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/images/logo.png' %}" width="60px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                <li><a href="{% url 'image:falls_images' %}">图片</a></li>
                <li><a href="{% url 'course:course_list' %}">课程</a></li>
                <li><a href="{% url 'course:about'%}">关于本站</a></li>
            </ul>


            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                    <li>
{#                        <a href="#">{{ user.username }}</a>    {# user是内置对象，直接调用就行 #}
                        <div class="dropdown" style="margin-top: 8px">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">{{ user.username }}<span class="caret"></span> </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:auth_passwordchange' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                                <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                            </ul>
                        </div>
                    </li>

                <li><a href="{% url 'account:auth_logout' %}">LOGOUT</a></li>
                {% else %}
                <li><a href="{% url 'account:auth_login' %}">Login</a></li>    {#)找到urls.py 中的name=user_login的path(先匹配MySite/urls.py  name='account'的字段一步一步向下寻找) #}
                <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}
{% block content %}

    <h1>this is home page</h1>

{% endblock %}

templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a> {% endif %}
    </span>
</div>